apiVersion: config.eda.nokia.com/v1alpha1
kind: Configlet
metadata:
  name: syslog
  namespace: clab-eda-st
spec:
  configs:
    - path: .system
      operation: Update
      config: |-
        {
          "logging": {
              "network-instance": "mgmt",
              "remote-server": [
                  {
                      "host": "100.82.85.164",
                      "transport": "udp",
                      "remote-port": 1514,
                      "facility": [
                          {
                              "facility-name": "local6",
                              "priority": {
                                  "match-above": "informational"
                              }
                          }
                      ]
                  }
              ]
          }
        }
  endpointSelector:
    - eda.nokia.com/role=leaf
    - eda.nokia.com/role=spine
  operatingSystem: srl
