apiVersion: v1
items:
  - apiVersion: interfaces.eda.nokia.com/v1alpha1
    kind: Interface
    metadata:
      generation: 1
      labels:
        eda.nokia.com/macvrf201: 'true'
        eda.nokia.com/macvrf1001: 'true'
        eda.nokia.com/role: edge
      name: lag-l1-l2-eth-1-1-lag-1-local
      namespace: eda-st
    spec:
      enabled: true
      encapType: dot1q
      ethernet:
        reloadDelayTimer: 60
        speed: 10G
        stormControl: {}
      lag:
        lacp:
          interval: fast
          mode: active
          systemPriority: 32768
        minLinks: 1
        multihoming:
          esi: auto
          mode: all-active
          reloadDelayTimer: 60
          revertive: false
        type: lacp
      lldp: true
      members:
        - enabled: true
          interface: ethernet-1-1
          lacpPortPriority: 32768
          node: leaf1
        - enabled: true
          interface: ethernet-1-1
          lacpPortPriority: 32768
          node: leaf2
      type: lag
  - apiVersion: interfaces.eda.nokia.com/v1alpha1
    kind: Interface
    metadata:
      generation: 1
      labels:
        eda.nokia.com/macvrf202: 'true'
        eda.nokia.com/macvrf1001: 'true'
        eda.nokia.com/role: edge
      name: lag-l1-l2-eth-1-2-lag-2-local
      namespace: eda-st
    spec:
      enabled: true
      encapType: dot1q
      ethernet:
        reloadDelayTimer: 60
        speed: 10G
        stormControl: {}
      lag:
        lacp:
          interval: fast
          mode: active
          systemPriority: 32768
        minLinks: 1
        multihoming:
          esi: auto
          mode: all-active
          reloadDelayTimer: 60
          revertive: false
        type: lacp
      lldp: true
      members:
        - enabled: true
          interface: ethernet-1-2
          lacpPortPriority: 32768
          node: leaf1
        - enabled: true
          interface: ethernet-1-2
          lacpPortPriority: 32768
          node: leaf2
      type: lag
  - apiVersion: interfaces.eda.nokia.com/v1alpha1
    kind: Interface
    metadata:
      generation: 1
      labels:
        eda.nokia.com/macvrf201: 'true'
        eda.nokia.com/macvrf1001: 'true'
        eda.nokia.com/role: edge
      name: lag-l3-l4-eth-1-1-lag-3-local
      namespace: eda-st
    spec:
      enabled: true
      encapType: dot1q
      ethernet:
        reloadDelayTimer: 60
        speed: 10G
        stormControl: {}
      lag:
        lacp:
          interval: fast
          mode: active
          systemPriority: 32768
        minLinks: 1
        multihoming:
          esi: auto
          mode: all-active
          reloadDelayTimer: 60
          revertive: false
        type: lacp
      lldp: true
      members:
        - enabled: true
          interface: ethernet-1-1
          lacpPortPriority: 32768
          node: leaf3
        - enabled: true
          interface: ethernet-1-1
          lacpPortPriority: 32768
          node: leaf4
      type: lag
  - apiVersion: interfaces.eda.nokia.com/v1alpha1
    kind: Interface
    metadata:
      generation: 1
      labels:
        eda.nokia.com/macvrf202: 'true'
        eda.nokia.com/macvrf1001: 'true'
        eda.nokia.com/role: edge
      name: lag-l3-l4-eth-1-2-lag-4-local
      namespace: eda-st
    spec:
      enabled: true
      encapType: dot1q
      ethernet:
        reloadDelayTimer: 60
        speed: 10G
        stormControl: {}
      lag:
        lacp:
          interval: fast
          mode: active
          systemPriority: 32768
        minLinks: 1
        multihoming:
          esi: auto
          mode: all-active
          reloadDelayTimer: 60
          revertive: false
        type: lacp
      lldp: true
      members:
        - enabled: true
          interface: ethernet-1-2
          lacpPortPriority: 32768
          node: leaf3
        - enabled: true
          interface: ethernet-1-2
          lacpPortPriority: 32768
          node: leaf4
      type: lag
kind: List
metadata:
  resourceVersion: ''
